import Image from "next/image";

export const metadata = {
  title: "Blog preview | Frontend Mentor",
  description: "Generated by create next app",
};

export default function page() {
  // - Mobile: 375px
  // - Desktop: 1440px

  return (
    <>
      <article className="relative border border-black z-20 bg-white w-[23rem] h-[32rem] p-5 rounded-xl flex flex-col justify-between">
        <Image
          className="rounded-xl"
          src="/blog_preview/ilustration-article.svg"
          width={350}
          height={200}
          alt="Code ilustration"
        />
        <span className="bg-yellow font-extrabold rounded-md w-[6rem] text-sm text-center px-[0.45rem]  py-[0.30rem]">
          Learning
        </span>
        <span className="text-sm">Published 21 Dev 2023</span>

        <a href="#" className="font-extrabold text-xl hover:text-yellow">HTML & CSS Foundations</a>

        <p className="text-grey_two">
          These languages are the backbone of every website, defining structure,
          content, and presentation.
        </p>

        <figure className="flex items-center gap-3">
          <Image
            src="/blog_preview/image-avatar.webp"
            width={40}
            height={40}
            alt="Avatar image"
          />
          <figcaption className="font-extrabold">Greg Hoooper</figcaption>
        </figure>
        {/* <div className="attribution">
        Challenge by{" "}
        <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
          Frontend Mentor
        </a>
        . Coded by <a href="#">Your Name Here</a>.
      </div> */}
      </article>
      <div className="top-50 left-50 ml-3 mt-3 lg:ml-4 lg:mt-4 absolute w-[23rem] h-[32rem] bg-black rounded-xl"></div>
    </>
  );
}
