import Image from "next/image";

export const metadata = {
  title: "Interactive rating component | Frontend Mentor",
  description: "Generated by create next app",
};

export default function page() {
  // - Mobile: 375px
  // - Desktop: 1440px

  return (
    <>
      {/* 
  <!-- Rating state start -->

  How did we do?

  Please let us know how we did with your support request. All feedback is appreciated 
  to help us improve our offering!

  1 2 3 4 5

  Submit

  <!-- Rating state end -->

  <!-- Thank you state start -->

  You selected <!-- Add rating here --> out of 5

  Thank you!

  We appreciate you taking the time to give a rating. If you ever need more support, 
  don’t hesitate to get in touch!

  <!-- Thank you state end --> */}
    </>
  );
}
