import Image from "next/image";

export const metadata = {
  title: "Ping coming soon page | Frontend Mentor",
  description: "Generated by create next app",
};

export default function page() {
  // - Mobile: 375px
  // - Desktop: 1440px

  // - Font size: 20px

//   For the social icons, you can use a font icon library. Some suggestions can be found below:
// - [Font Awesome](https://fontawesome.com)
// - [IcoMoon](https://icomoon.io)
// - [Ionicons](https://ionicons.com)

  return (
    <>
      {/*   We are launching soon!

  Subscribe and get notified

  Notify Me

  &copy; Copyright Ping. All rights reserved. */}
    </>
  );
}
