import Image from "next/image";

export const metadata = {
  title: "Base Apparel coming soon page | Frontend Mentor",
  description: "Generated by create next app",
};

export default function page() {
  // - Mobile: 375px
  // - Desktop: 1440px

  return (
    <>
      <div className="w-[60%] h-full bg-light_pink p-20 justify-around">
        <Image
          src="/appareal_page/logo.svg"
          width={158}
          height={33}
          alt="Appareal logo"
        />

        <div className="flex flex-col gap-5">
          <h1 className="text-9xl uppercase font-semibold">
            <span className="font-light">We&apos;re</span> coming soon
          </h1>

          <p>
            Hello fellow shoppers! We&apos;re currently building our new fashion
            store. Add your email below to stay up-to-date with announcements
            and our launch deals.
          </p>

          <form>
            <input type="text"></input>
            <button className="px-5 py-3 bg-gradient-linear-pink rounded-xl" type="submit">
              <Image
                src="/appareal_page/icon-arrow.svg"
                width={12}
                height={20}
              />
            </button>
          </form>
        </div>
      </div>

      <figure className="w-[40%] h-full relative">
        <Image fill src="/appareal_page/hero-desktop.jpg" alt="Woman model" />
      </figure>
    </>
  );
}