import Image from "next/image";

export const metadata = {
  title: "Intro component with sign up form | Frontend Mentor",
  description: "Generated by create next app",
};

export default function page() {
  // - Mobile: 375px
  // - Desktop: 1440px

  // - Font size: 16px

//   For the social icons, you can use a font icon library. Some suggestions can be found below:
// - [Font Awesome](https://fontawesome.com)
// - [IcoMoon](https://icomoon.io)
// - [Ionicons](https://ionicons.com)

  return (
    <>
      {/* 

  Learn to code by watching others

  See how experienced developers solve problems in real-time. Watching scripted tutorials is great, 
  but understanding how developers think is invaluable. 

  Try it free 7 days then $20/mo. thereafter

  First Name 
  Last Name 
  Email Address
  Password

  Claim your free trial 

  By clicking the button, you are agreeing to our Terms and Services */}
    </>
  );
}
