import Image from "next/image";
import { Young_Serif } from "next/font/google";

const young_serif = Young_Serif({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Recipe Page | Frontend Mentor",
  description: "Generated by create next app",
};

export default function page() {
// - Mobile: 375px
// - Desktop: 1440px

  return (
    <>
      <header className="lg:p-10">
        <figure className="w-full h-[20rem] lg:h-[40rem] relative mb-10">
          <Image
            className="rounded-none lg:rounded-xl object-cover"
            src="/recipe_page/image-omelette.jpeg"
            fill={true}
            alt="Omelette on a plate"
            priority
          />
        </figure>
      </header>

      <section className="p-10">
        <h1 className={`${young_serif.className} text-4xl mb-10`}>
          Simple Omelette Recipe
        </h1>
        <p>
          An easy and quick dish, perfect for any meal. This classic omelette
          combines beaten eggs cooked to perfection, optionally filled with your
          choice of cheese, vegetables, or meats.
        </p>

        <div className={`bg-rose_white rounded-xl p-10  my-10`}>
          <h3 className={`text-xl font-semibold text-dark_raspberry`}>
            Preparation time
          </h3>
          <ul className="list-disc list-inside">
            <li>
              <strong className="ml-4 font-bold text-lg">Total:</strong>{" "}
              Approximately 10 minutes
            </li>
            <li>
              <strong className="ml-4 font-bold text-lg">Preparation:</strong> 5
              minutes
            </li>
            <li>
              <strong className="ml-4 font-bold text-lg">Cooking:</strong> 5
              minutes
            </li>
          </ul>
        </div>

        <h2 className={`${young_serif.className} text-nutmeg text-2xl mb-10`}>
          Ingredients
        </h2>
        <ul className="list-disc list-inside mb-10">
          <li>
            <span className="ml-4">2-3 large eggs</span>
          </li>
          <li>
            <span className="ml-4">Salt, to taste</span>
          </li>
          <li>
            <span className="ml-4">Pepper, to taste</span>
          </li>
          <li>
            <span className="ml-4">1 tablespoon of butter or oil</span>
          </li>
          <li>
            <span className="ml-4">
              Optional fillings: cheese, diced vegetables, cooked meats, herbs
            </span>
          </li>
        </ul>
        <hr className="border-light_grey mb-10" />
        <h2 className={`${young_serif.className} text-nutmeg text-2xl mb-10`}>
          Instructions
        </h2>
        <ol className="list-decimal list-inside text-nutmeg font-bold">
          <li>
            <strong className="text-dark_charchoal ml-4 font-bold text-lg">
              Beat the eggs:
            </strong>{" "}
            <span className="font-normal text-dark_charchoal">
              In a bowl, beat the eggs with a pinch of salt and pepper until
              they are well mixed. You can add a tablespoon of water or milk for
              a fluffier texture.
            </span>
          </li>
          <li>
            <strong className="text-dark_charchoal ml-4 font-bold text-lg">
              Heat the pan:
            </strong>{" "}
            <span className="font-normal text-dark_charchoal">
              Place a non-stick frying pan over medium heat and add butter or
              oil.
            </span>
          </li>
          <li>
            <strong className="text-dark_charchoal ml-4 font-bold text-lg">
              Cook the omelette:
            </strong>{" "}
            <span className="font-normal text-dark_charchoal">
              Once the butter is melted and bubbling, pour in the eggs. Tilt the
              pan to ensure the eggs evenly coat the surface.
            </span>
          </li>
          <li>
            <strong className="text-dark_charchoal ml-4 font-bold text-lg">
              Add fillings (optional):
            </strong>{" "}
            <span className="font-normal text-dark_charchoal">
              When the eggs begin to set at the edges but are still slightly
              runny in the middle, sprinkle your chosen fillings over one half
              of the omelette.
            </span>
          </li>
          <li>
            <strong className="text-dark_charchoal ml-4 font-bold text-lg">
              Fold and serve:
            </strong>{" "}
            <span className="font-normal text-dark_charchoal">
              As the omelette continues to cook, carefully lift one edge and
              fold it over the fillings. Let it cook for another minute, then
              slide it onto a plate.
            </span>
          </li>
          <li>
            <strong className="text-dark_charchoal ml-4 font-bold text-lg">
              Enjoy:
            </strong>{" "}
            <span className="font-normal text-dark_charchoal">
              Serve hot, with additional salt and pepper if needed.
            </span>
          </li>
        </ol>

        <hr className="border-light_grey my-10" />

        <h2 className={`${young_serif.className} text-nutmeg text-2xl mb-10`}>
          Nutrition
        </h2>

        <table className="table-fixed w-full text-lg">
          <caption className="mb-5 text-left">
            The table below shows nutritional values per serving without the
            additional fillings.
          </caption>
          <thead className="w-full mb-4">
            <tr className="w-full border-b border-light_grey">
              <th className="pl-10 py-5 text-left font-normal">Calories</th>
              <td className=" pl-10 font-semibold text-nutmeg">277kcal</td>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-light_grey">
              <td className="pl-10 py-5">Carbs</td>
              <td className="pl-10 py-5 font-semibold text-nutmeg">0g</td>
            </tr>
            <tr className="border-b border-light_grey">
              <td className="pl-10 py-5">Protein</td>
              <td className=" pl-10 py-5 font-semibold text-nutmeg">20g</td>
            </tr>
            <tr className="border-none">
              <td className="pl-10 py-5">Fat</td>
              <td className=" pl-10 py-5 font-semibold text-nutmeg">22g</td>
            </tr>
          </tbody>
        </table>
      </section>

      {/* <div className="attribution">
        Challenge by{" "}
        <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
          Frontend Mentor
        </a>
        . Coded by <a href="#">Your Name Here</a>.
      </div> */}
    </>
  );
}
